# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './DesignerFiles/EditProfile.ui'
#
# Created: Fri Aug 11 14:23:21 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_editProfileDialog(object):
    def setupUi(self, editProfileDialog):
        editProfileDialog.setObjectName("editProfileDialog")
        editProfileDialog.setWindowModality(QtCore.Qt.NonModal)
        editProfileDialog.setEnabled(True)
        editProfileDialog.resize(800, 600)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(editProfileDialog.sizePolicy().hasHeightForWidth())
        editProfileDialog.setSizePolicy(sizePolicy)
        editProfileDialog.setMinimumSize(QtCore.QSize(0, 0))
        editProfileDialog.setMaximumSize(QtCore.QSize(800, 800))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Pictures/GearIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        editProfileDialog.setWindowIcon(icon)
        editProfileDialog.setWindowFilePath("")
        editProfileDialog.setModal(False)
        self.gridLayout = QtGui.QGridLayout(editProfileDialog)
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtGui.QFrame(editProfileDialog)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtGui.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.buttonBox = QtGui.QDialogButtonBox(self.frame)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Save)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 4, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.frame)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.South)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_personal = QtGui.QWidget()
        self.tab_personal.setObjectName("tab_personal")
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_personal)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.l_rank = QtGui.QLabel(self.tab_personal)
        self.l_rank.setObjectName("l_rank")
        self.gridLayout_3.addWidget(self.l_rank, 0, 0, 1, 1)
        self.rankBox = QtGui.QComboBox(self.tab_personal)
        self.rankBox.setObjectName("rankBox")
        self.gridLayout_3.addWidget(self.rankBox, 0, 1, 1, 1)
        self.l_first = QtGui.QLabel(self.tab_personal)
        self.l_first.setObjectName("l_first")
        self.gridLayout_3.addWidget(self.l_first, 0, 2, 1, 1)
        self.firstEdit = QtGui.QLineEdit(self.tab_personal)
        self.firstEdit.setMinimumSize(QtCore.QSize(130, 30))
        self.firstEdit.setMaxLength(20)
        self.firstEdit.setObjectName("firstEdit")
        self.gridLayout_3.addWidget(self.firstEdit, 0, 3, 1, 3)
        self.l_middle = QtGui.QLabel(self.tab_personal)
        self.l_middle.setObjectName("l_middle")
        self.gridLayout_3.addWidget(self.l_middle, 0, 6, 1, 1)
        self.middleEdit = QtGui.QLineEdit(self.tab_personal)
        self.middleEdit.setMinimumSize(QtCore.QSize(130, 30))
        self.middleEdit.setMaxLength(20)
        self.middleEdit.setObjectName("middleEdit")
        self.gridLayout_3.addWidget(self.middleEdit, 0, 7, 1, 3)
        self.l_last = QtGui.QLabel(self.tab_personal)
        self.l_last.setObjectName("l_last")
        self.gridLayout_3.addWidget(self.l_last, 0, 10, 1, 1)
        self.lastEdit = QtGui.QLineEdit(self.tab_personal)
        self.lastEdit.setMinimumSize(QtCore.QSize(130, 30))
        self.lastEdit.setMaxLength(20)
        self.lastEdit.setObjectName("lastEdit")
        self.gridLayout_3.addWidget(self.lastEdit, 0, 11, 1, 2)
        self.suffixBox = QtGui.QComboBox(self.tab_personal)
        self.suffixBox.setObjectName("suffixBox")
        self.gridLayout_3.addWidget(self.suffixBox, 0, 13, 1, 1)
        self.line = QtGui.QFrame(self.tab_personal)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 1, 0, 1, 14)
        self.l_edipi = QtGui.QLabel(self.tab_personal)
        self.l_edipi.setMargin(0)
        self.l_edipi.setObjectName("l_edipi")
        self.gridLayout_3.addWidget(self.l_edipi, 2, 0, 2, 1)
        self.edipiEdit = QtGui.QLineEdit(self.tab_personal)
        self.edipiEdit.setMaxLength(10)
        self.edipiEdit.setObjectName("edipiEdit")
        self.gridLayout_3.addWidget(self.edipiEdit, 3, 1, 1, 2)
        self.l_last4 = QtGui.QLabel(self.tab_personal)
        self.l_last4.setMargin(0)
        self.l_last4.setObjectName("l_last4")
        self.gridLayout_3.addWidget(self.l_last4, 3, 4, 1, 1)
        self.last4Edit = QtGui.QLineEdit(self.tab_personal)
        self.last4Edit.setMaxLength(4)
        self.last4Edit.setObjectName("last4Edit")
        self.gridLayout_3.addWidget(self.last4Edit, 3, 5, 1, 1)
        self.l_mealCard = QtGui.QLabel(self.tab_personal)
        self.l_mealCard.setMargin(0)
        self.l_mealCard.setObjectName("l_mealCard")
        self.gridLayout_3.addWidget(self.l_mealCard, 3, 6, 1, 2)
        self.mealCardEdit = QtGui.QLineEdit(self.tab_personal)
        self.mealCardEdit.setMaxLength(11)
        self.mealCardEdit.setObjectName("mealCardEdit")
        self.gridLayout_3.addWidget(self.mealCardEdit, 3, 8, 1, 3)
        self.l_dob = QtGui.QLabel(self.tab_personal)
        self.l_dob.setMargin(0)
        self.l_dob.setObjectName("l_dob")
        self.gridLayout_3.addWidget(self.l_dob, 3, 11, 1, 1)
        self.dobEdit = QtGui.QDateEdit(self.tab_personal)
        self.dobEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2090, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dobEdit.setDate(QtCore.QDate(2090, 1, 1))
        self.dobEdit.setCalendarPopup(True)
        self.dobEdit.setObjectName("dobEdit")
        self.gridLayout_3.addWidget(self.dobEdit, 3, 12, 1, 2)
        self.line_2 = QtGui.QFrame(self.tab_personal)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_3.addWidget(self.line_2, 4, 0, 1, 14)
        self.l_eas = QtGui.QLabel(self.tab_personal)
        self.l_eas.setMargin(0)
        self.l_eas.setObjectName("l_eas")
        self.gridLayout_3.addWidget(self.l_eas, 5, 0, 3, 1)
        self.l_mos = QtGui.QLabel(self.tab_personal)
        self.l_mos.setObjectName("l_mos")
        self.gridLayout_3.addWidget(self.l_mos, 5, 4, 3, 1)
        self.l_superRankName = QtGui.QLabel(self.tab_personal)
        self.l_superRankName.setObjectName("l_superRankName")
        self.gridLayout_3.addWidget(self.l_superRankName, 5, 7, 3, 2)
        self.easEdit = QtGui.QDateEdit(self.tab_personal)
        self.easEdit.setObjectName("easEdit")
        self.gridLayout_3.addWidget(self.easEdit, 6, 1, 2, 2)
        self.mosEdit = QtGui.QLineEdit(self.tab_personal)
        self.mosEdit.setMaxLength(4)
        self.mosEdit.setObjectName("mosEdit")
        self.gridLayout_3.addWidget(self.mosEdit, 6, 5, 2, 1)
        self.superLastEdit = QtGui.QLineEdit(self.tab_personal)
        self.superLastEdit.setMaxLength(20)
        self.superLastEdit.setObjectName("superLastEdit")
        self.gridLayout_3.addWidget(self.superLastEdit, 6, 10, 2, 3)
        self.superRankBox = QtGui.QComboBox(self.tab_personal)
        self.superRankBox.setObjectName("superRankBox")
        self.gridLayout_3.addWidget(self.superRankBox, 7, 9, 1, 1)
        self.l_billet = QtGui.QLabel(self.tab_personal)
        self.l_billet.setObjectName("l_billet")
        self.gridLayout_3.addWidget(self.l_billet, 8, 0, 1, 1)
        self.billetBox = QtGui.QComboBox(self.tab_personal)
        self.billetBox.setMinimumSize(QtCore.QSize(140, 30))
        self.billetBox.setObjectName("billetBox")
        self.gridLayout_3.addWidget(self.billetBox, 8, 1, 1, 4)
        self.billetEdit = QtGui.QLineEdit(self.tab_personal)
        self.billetEdit.setEnabled(True)
        self.billetEdit.setMaxLength(20)
        self.billetEdit.setReadOnly(False)
        self.billetEdit.setObjectName("billetEdit")
        self.gridLayout_3.addWidget(self.billetEdit, 8, 5, 1, 2)
        self.l_blood = QtGui.QLabel(self.tab_personal)
        self.l_blood.setObjectName("l_blood")
        self.gridLayout_3.addWidget(self.l_blood, 8, 7, 1, 2)
        self.bloodBox = QtGui.QComboBox(self.tab_personal)
        self.bloodBox.setObjectName("bloodBox")
        self.gridLayout_3.addWidget(self.bloodBox, 8, 9, 1, 1)
        self.l_rfid = QtGui.QLabel(self.tab_personal)
        self.l_rfid.setAlignment(QtCore.Qt.AlignCenter)
        self.l_rfid.setObjectName("l_rfid")
        self.gridLayout_3.addWidget(self.l_rfid, 9, 1, 1, 1)
        self.rfidEdit = QtGui.QTextEdit(self.tab_personal)
        self.rfidEdit.setTabStopWidth(30)
        self.rfidEdit.setObjectName("rfidEdit")
        self.gridLayout_3.addWidget(self.rfidEdit, 10, 0, 1, 3)
        self.line_3 = QtGui.QFrame(self.tab_personal)
        self.line_3.setEnabled(True)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_3.addWidget(self.line_3, 11, 0, 1, 14)
        self.allergyEdit = QtGui.QTextEdit(self.tab_personal)
        self.allergyEdit.setObjectName("allergyEdit")
        self.gridLayout_3.addWidget(self.allergyEdit, 10, 11, 1, 3)
        self.l_allergies = QtGui.QLabel(self.tab_personal)
        self.l_allergies.setObjectName("l_allergies")
        self.gridLayout_3.addWidget(self.l_allergies, 9, 12, 1, 1)
        self.tabWidget.addTab(self.tab_personal, "")
        self.tab_contact = QtGui.QWidget()
        self.tab_contact.setObjectName("tab_contact")
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_contact)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.l_email = QtGui.QLabel(self.tab_contact)
        self.l_email.setAlignment(QtCore.Qt.AlignCenter)
        self.l_email.setObjectName("l_email")
        self.gridLayout_4.addWidget(self.l_email, 0, 0, 1, 1)
        self.emailEdit = QtGui.QLineEdit(self.tab_contact)
        self.emailEdit.setMaxLength(50)
        self.emailEdit.setObjectName("emailEdit")
        self.gridLayout_4.addWidget(self.emailEdit, 0, 1, 1, 1)
        self.l_homePhone = QtGui.QLabel(self.tab_contact)
        self.l_homePhone.setAlignment(QtCore.Qt.AlignCenter)
        self.l_homePhone.setObjectName("l_homePhone")
        self.gridLayout_4.addWidget(self.l_homePhone, 1, 0, 1, 1)
        self.homePhoneEdit = QtGui.QLineEdit(self.tab_contact)
        self.homePhoneEdit.setMaxLength(14)
        self.homePhoneEdit.setObjectName("homePhoneEdit")
        self.gridLayout_4.addWidget(self.homePhoneEdit, 1, 1, 1, 1)
        self.l_cell = QtGui.QLabel(self.tab_contact)
        self.l_cell.setAlignment(QtCore.Qt.AlignCenter)
        self.l_cell.setObjectName("l_cell")
        self.gridLayout_4.addWidget(self.l_cell, 2, 0, 1, 1)
        self.lineEdit_3 = QtGui.QLineEdit(self.tab_contact)
        self.lineEdit_3.setMaxLength(14)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_4.addWidget(self.lineEdit_3, 2, 1, 1, 1)
        self.l_resident = QtGui.QLabel(self.tab_contact)
        self.l_resident.setAlignment(QtCore.Qt.AlignCenter)
        self.l_resident.setObjectName("l_resident")
        self.gridLayout_4.addWidget(self.l_resident, 3, 0, 1, 1)
        self.residentialEdit = QtGui.QTextEdit(self.tab_contact)
        self.residentialEdit.setObjectName("residentialEdit")
        self.gridLayout_4.addWidget(self.residentialEdit, 3, 1, 1, 1)
        self.l_mailing = QtGui.QLabel(self.tab_contact)
        self.l_mailing.setAlignment(QtCore.Qt.AlignCenter)
        self.l_mailing.setObjectName("l_mailing")
        self.gridLayout_4.addWidget(self.l_mailing, 4, 0, 1, 1)
        self.mailingEdit = QtGui.QTextEdit(self.tab_contact)
        self.mailingEdit.setObjectName("mailingEdit")
        self.gridLayout_4.addWidget(self.mailingEdit, 4, 1, 1, 1)
        self.tabWidget.addTab(self.tab_contact, "")
        self.tab_training = QtGui.QWidget()
        self.tab_training.setObjectName("tab_training")
        self.pvsSerial = QtGui.QLineEdit(self.tab_training)
        self.pvsSerial.setGeometry(QtCore.QRect(139, 126, 148, 33))
        self.pvsSerial.setMaxLength(40)
        self.pvsSerial.setObjectName("pvsSerial")
        self.rifleSerial = QtGui.QLineEdit(self.tab_training)
        self.rifleSerial.setGeometry(QtCore.QRect(139, 9, 148, 33))
        self.rifleSerial.setMaxLength(40)
        self.rifleSerial.setObjectName("rifleSerial")
        self.l_rifleSerial = QtGui.QLabel(self.tab_training)
        self.l_rifleSerial.setGeometry(QtCore.QRect(10, 10, 91, 21))
        self.l_rifleSerial.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.l_rifleSerial.setObjectName("l_rifleSerial")
        self.pistolSerial = QtGui.QLineEdit(self.tab_training)
        self.pistolSerial.setGeometry(QtCore.QRect(139, 48, 148, 33))
        self.pistolSerial.setMaxLength(40)
        self.pistolSerial.setObjectName("pistolSerial")
        self.l_pistolSerial = QtGui.QLabel(self.tab_training)
        self.l_pistolSerial.setGeometry(QtCore.QRect(10, 50, 51, 21))
        self.l_pistolSerial.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.l_pistolSerial.setObjectName("l_pistolSerial")
        self.peqSerial = QtGui.QLineEdit(self.tab_training)
        self.peqSerial.setGeometry(QtCore.QRect(139, 87, 148, 33))
        self.peqSerial.setMaxLength(40)
        self.peqSerial.setObjectName("peqSerial")
        self.l_peqSerial = QtGui.QLabel(self.tab_training)
        self.l_peqSerial.setGeometry(QtCore.QRect(10, 90, 81, 21))
        self.l_peqSerial.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.l_peqSerial.setObjectName("l_peqSerial")
        self.l_pvsSerial = QtGui.QLabel(self.tab_training)
        self.l_pvsSerial.setGeometry(QtCore.QRect(10, 130, 91, 21))
        self.l_pvsSerial.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.l_pvsSerial.setObjectName("l_pvsSerial")
        self.mwrapCheck = QtGui.QCheckBox(self.tab_training)
        self.mwrapCheck.setGeometry(QtCore.QRect(290, 190, 75, 26))
        self.mwrapCheck.setObjectName("mwrapCheck")
        self.stonCheck = QtGui.QCheckBox(self.tab_training)
        self.stonCheck.setGeometry(QtCore.QRect(150, 190, 74, 26))
        self.stonCheck.setObjectName("stonCheck")
        self.hmmwvCheck = QtGui.QCheckBox(self.tab_training)
        self.hmmwvCheck.setGeometry(QtCore.QRect(10, 190, 93, 26))
        self.hmmwvCheck.setObjectName("hmmwvCheck")
        self.tableWidget = QtGui.QTableWidget(self.tab_training)
        self.tableWidget.setGeometry(QtCore.QRect(440, 260, 311, 221))
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.dlptScore = QtGui.QLineEdit(self.tab_training)
        self.dlptScore.setGeometry(QtCore.QRect(522, 100, 211, 33))
        self.dlptScore.setObjectName("dlptScore")
        self.dlptLanguage = QtGui.QLineEdit(self.tab_training)
        self.dlptLanguage.setGeometry(QtCore.QRect(522, 10, 211, 33))
        self.dlptLanguage.setObjectName("dlptLanguage")
        self.dlptDate = QtGui.QDateEdit(self.tab_training)
        self.dlptDate.setGeometry(QtCore.QRect(520, 60, 211, 33))
        self.dlptDate.setDate(QtCore.QDate(2015, 1, 1))
        self.dlptDate.setCalendarPopup(True)
        self.dlptDate.setObjectName("dlptDate")
        self.line_4 = QtGui.QFrame(self.tab_training)
        self.line_4.setGeometry(QtCore.QRect(370, -10, 20, 501))
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.buttonRemove = QtGui.QPushButton(self.tab_training)
        self.buttonRemove.setGeometry(QtCore.QRect(620, 160, 101, 31))
        self.buttonRemove.setObjectName("buttonRemove")
        self.buttonAdd = QtGui.QPushButton(self.tab_training)
        self.buttonAdd.setGeometry(QtCore.QRect(480, 160, 101, 31))
        self.buttonAdd.setObjectName("buttonAdd")
        self.l_dlpt_language = QtGui.QLabel(self.tab_training)
        self.l_dlpt_language.setGeometry(QtCore.QRect(390, 10, 121, 31))
        self.l_dlpt_language.setAlignment(QtCore.Qt.AlignCenter)
        self.l_dlpt_language.setObjectName("l_dlpt_language")
        self.l_dlpt_date = QtGui.QLabel(self.tab_training)
        self.l_dlpt_date.setGeometry(QtCore.QRect(400, 60, 91, 31))
        self.l_dlpt_date.setAlignment(QtCore.Qt.AlignCenter)
        self.l_dlpt_date.setObjectName("l_dlpt_date")
        self.l_dlpt_score = QtGui.QLabel(self.tab_training)
        self.l_dlpt_score.setGeometry(QtCore.QRect(400, 100, 91, 31))
        self.l_dlpt_score.setAlignment(QtCore.Qt.AlignCenter)
        self.l_dlpt_score.setObjectName("l_dlpt_score")
        self.tabWidget.addTab(self.tab_training, "")
        self.tab_dependants = QtGui.QWidget()
        self.tab_dependants.setObjectName("tab_dependants")
        self.tabWidget.addTab(self.tab_dependants, "")
        self.tab_appointments = QtGui.QWidget()
        self.tab_appointments.setObjectName("tab_appointments")
        self.tabWidget.addTab(self.tab_appointments, "")
        self.gridLayout_2.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 1, 1, 1)

        self.retranslateUi(editProfileDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(editProfileDialog)

    def retranslateUi(self, editProfileDialog):
        editProfileDialog.setWindowTitle(QtGui.QApplication.translate("editProfileDialog", "Edit Profile", None, QtGui.QApplication.UnicodeUTF8))
        self.l_rank.setText(QtGui.QApplication.translate("editProfileDialog", "Rank", None, QtGui.QApplication.UnicodeUTF8))
        self.l_first.setText(QtGui.QApplication.translate("editProfileDialog", "First", None, QtGui.QApplication.UnicodeUTF8))
        self.l_middle.setText(QtGui.QApplication.translate("editProfileDialog", "Middle", None, QtGui.QApplication.UnicodeUTF8))
        self.l_last.setText(QtGui.QApplication.translate("editProfileDialog", "Last", None, QtGui.QApplication.UnicodeUTF8))
        self.l_edipi.setText(QtGui.QApplication.translate("editProfileDialog", "EDIPI", None, QtGui.QApplication.UnicodeUTF8))
        self.l_last4.setText(QtGui.QApplication.translate("editProfileDialog", "Last 4", None, QtGui.QApplication.UnicodeUTF8))
        self.l_mealCard.setText(QtGui.QApplication.translate("editProfileDialog", "Meal Card", None, QtGui.QApplication.UnicodeUTF8))
        self.l_dob.setText(QtGui.QApplication.translate("editProfileDialog", "DOB", None, QtGui.QApplication.UnicodeUTF8))
        self.l_eas.setText(QtGui.QApplication.translate("editProfileDialog", "EAS", None, QtGui.QApplication.UnicodeUTF8))
        self.l_mos.setText(QtGui.QApplication.translate("editProfileDialog", "MOS", None, QtGui.QApplication.UnicodeUTF8))
        self.l_superRankName.setText(QtGui.QApplication.translate("editProfileDialog", "Supervisor", None, QtGui.QApplication.UnicodeUTF8))
        self.l_billet.setText(QtGui.QApplication.translate("editProfileDialog", "Billet", None, QtGui.QApplication.UnicodeUTF8))
        self.l_blood.setText(QtGui.QApplication.translate("editProfileDialog", "Blood Type", None, QtGui.QApplication.UnicodeUTF8))
        self.l_rfid.setText(QtGui.QApplication.translate("editProfileDialog", "RFID", None, QtGui.QApplication.UnicodeUTF8))
        self.l_allergies.setText(QtGui.QApplication.translate("editProfileDialog", "Allergies", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_personal), QtGui.QApplication.translate("editProfileDialog", "Personal", None, QtGui.QApplication.UnicodeUTF8))
        self.l_email.setText(QtGui.QApplication.translate("editProfileDialog", "Email Address", None, QtGui.QApplication.UnicodeUTF8))
        self.l_homePhone.setText(QtGui.QApplication.translate("editProfileDialog", "Home Phone", None, QtGui.QApplication.UnicodeUTF8))
        self.l_cell.setText(QtGui.QApplication.translate("editProfileDialog", "Cell Phone", None, QtGui.QApplication.UnicodeUTF8))
        self.l_resident.setText(QtGui.QApplication.translate("editProfileDialog", "Residential Address", None, QtGui.QApplication.UnicodeUTF8))
        self.l_mailing.setText(QtGui.QApplication.translate("editProfileDialog", "Mailing Address", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_contact), QtGui.QApplication.translate("editProfileDialog", "Contact", None, QtGui.QApplication.UnicodeUTF8))
        self.l_rifleSerial.setText(QtGui.QApplication.translate("editProfileDialog", "M16/M4 Serial", None, QtGui.QApplication.UnicodeUTF8))
        self.l_pistolSerial.setText(QtGui.QApplication.translate("editProfileDialog", "M9 Serial", None, QtGui.QApplication.UnicodeUTF8))
        self.l_peqSerial.setText(QtGui.QApplication.translate("editProfileDialog", "PEQ-15 Serial", None, QtGui.QApplication.UnicodeUTF8))
        self.l_pvsSerial.setText(QtGui.QApplication.translate("editProfileDialog", "AN/PVS-14 Serial", None, QtGui.QApplication.UnicodeUTF8))
        self.mwrapCheck.setText(QtGui.QApplication.translate("editProfileDialog", "MRAP", None, QtGui.QApplication.UnicodeUTF8))
        self.stonCheck.setText(QtGui.QApplication.translate("editProfileDialog", "7-TON", None, QtGui.QApplication.UnicodeUTF8))
        self.hmmwvCheck.setText(QtGui.QApplication.translate("editProfileDialog", "HMMWV", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("editProfileDialog", "DLPT", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("editProfileDialog", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("editProfileDialog", "Score", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonRemove.setText(QtGui.QApplication.translate("editProfileDialog", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonAdd.setText(QtGui.QApplication.translate("editProfileDialog", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.l_dlpt_language.setText(QtGui.QApplication.translate("editProfileDialog", "DLPT Language", None, QtGui.QApplication.UnicodeUTF8))
        self.l_dlpt_date.setText(QtGui.QApplication.translate("editProfileDialog", "DLPT Date", None, QtGui.QApplication.UnicodeUTF8))
        self.l_dlpt_score.setText(QtGui.QApplication.translate("editProfileDialog", "DLPT Score", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_training), QtGui.QApplication.translate("editProfileDialog", "Training", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_dependants), QtGui.QApplication.translate("editProfileDialog", "Dependants", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_appointments), QtGui.QApplication.translate("editProfileDialog", "Appointments", None, QtGui.QApplication.UnicodeUTF8))

